set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(MINGW_TRIPLET x86_64-w64-mingw32)

set(CMAKE_C_COMPILER   ${MINGW_TRIPLET}-gcc)
set(CMAKE_CXX_COMPILER ${MINGW_TRIPLET}-g++)
set(CMAKE_RC_COMPILER  ${MINGW_TRIPLET}-windres)
set(CMAKE_AR           ${MINGW_TRIPLET}-ar)
set(CMAKE_RANLIB       ${MINGW_TRIPLET}-ranlib)
set(CMAKE_STRIP        ${MINGW_TRIPLET}-strip)

set(CMAKE_FIND_ROOT_PATH /usr/${MINGW_TRIPLET})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_CXX_FLAGS_INIT "-D__USE_MINGW_ANSI_STDIO=1 -DUNICODE -D_UNICODE")
set(CMAKE_C_FLAGS_INIT   "-D__USE_MINGW_ANSI_STDIO=1 -DUNICODE -D_UNICODE")

set(CMAKE_EXE_LINKER_FLAGS_INIT    "-static-libgcc -static-libstdc++ -Wl,-Bstatic,--whole-archive -lwinpthread -Wl,--no-whole-archive -Wl,-Bdynamic")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-static-libgcc -static-libstdc++")
